//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public int LeaveTypeId { get; set; }
        public string LeaveName { get; set; }
        public string LeaveDescription { get; set; }
        public Nullable<int> NumberOfDaysAllowed { get; set; }
    }
}
